name: Documentation

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Generate API documentation
        run: |
          # Generate docs for each package with DMT theme
          for pkg in packages/*/; do
            if [ -f "$pkg/package.json" ]; then
              echo "Generating docs for $pkg"
              cd "$pkg"
              pnpm exec typedoc --options ../../typedoc.json \
                      --out ../../docs/api/$(basename $pkg) \
                      src/index.ts || true
              cd ../..
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: github.ref == 'refs/heads/master'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: './docs'

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
